### ISSUE TITLE
Typo in command name

### ISSUE THREAD

**Issue by mrchief** [teppeis/closure-ts#36]
https://github.com/teppeis/closure-ts/blob/master/package.json#L7 should be `clsourets > closurets`

**Comment by teppeis** [comment]
wow :smile:

**Comment by lukaw3d** [comment]
This still seems to remain an issue on npm https://www.npmjs.com/package/closure-ts (published by @geekdenz)

**Comment by geekdenz** [comment]
Will fix it when I get a chance.
